#!/bin/ksh

test() {
    CMD="$1"
    no="$2"
    kash_out=$(printf "%s" "$CMD" | ./build/kash)
    ksh_out=$(printf "%s" "$CMD" | ksh)
    if [ "$kash_out" = "$ksh_out" ]; then
        printf "%s: %s: \033[32mpassed\033[0m\n" "$no" "$CMD"
    else
        printf "%s: %s: \033[31mfailed\033[0m\n" "$no" "$CMD"
        #printf "kash: \033[4m\033[31m%s\033[0m; ksh: \033[4m\033[32m%s\033[0m\n" "$kash_out" "$ksh_out"
    fi
}

cmds=("ls"
    "exit"
    "exit; echo hello"
    "echo hello world"
    'echo "hello world"'
    "echo 'hello world'"
    "ls | wc -l"
    'printf "%s\n" "$HOME"')

for i in $(seq 0 $((${#cmds[@]} - 1))); do
    test "${cmds[$i]}" "$i"
done
